# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: sqlite3
  encoding: unicode
  database: applicant_resume
  pool: 5
  username: name
  password: secret

test:
  adapter: sqlite3
  encoding: unicode
  database: applicant_resume
  pool: 5
  username: name
  password: secret

production:
  adapter: sqlite3
  encoding: unicode
  database: applicant_resume
  pool: 5
  username: name
  password: secret
