# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3efd988f79c36288565b8df8db51cd332812d25e55e96f707da1dbad7dbc2e9e38d4c47330ad02677a0c091ceda96120b8a890d2de665f1602e883f080fe8f74

test:
  secret_key_base: 7ff173151fec4326e6f1e7d0bee3cc547db5f258ff8a9b7e7897be2eea04458511d778b11201b395f1679a6ad5c2ac0e983130a9c1557c7a3dfbf8689789533c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
